### ISSUE TITLE
[SUGGESTION] Network Variables

### ISSUE THREAD

**Issue by Lennord** [byPixelTV/SkCloudnet#3]
### Suggestion

Good evening, it would be nice to add a system of synchronized variables for all Minecraft servers.

I think it would be a good idea for the future of the skript addon plugin.

### Alternatives

_**NONE**_

**Comment by darkwolfie37** [comment]
Just to add comment here, Skript is working on getting network variables online. I have tested some PR builds and it seems to work just fine. [#5646](https://github.com/SkriptLang/Skript/pull/5646)

**Comment by byPixelTV** [comment]
Not exactly network variables, but it is for storing variables in an SQL database, and yes, it is a good replacement for using network variables.
